<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="third_party\androidx\compose\material3\LICENSE-APACHE-2.0.txt" Pack="true" PackagePath="\" />
        <None Include="third_party\androidx\compose\material3\NOTICE.txt" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.3.7" />
      <PackageReference Include="Bdziam.DynamicColor" Version="0.0.11" />
    </ItemGroup>
    
    <ItemGroup>
        <AvaloniaResource Include="Assets\Fonts\**\*.ttf" />
    </ItemGroup>
    
    <ItemGroup>
      <AdditionalFiles Include="Tokens\Component\Button.axaml" />
    </ItemGroup>

</Project>
